openapi: 3.0.3
info:
  title: JWT Login API
  version: 1.0.0
  description: API docs cho hệ thống login với JWT + Product CRUD

servers:
  - url: http://localhost:3000/api
    description: Local development server
tags:
  - name: Auth
    description: Xác thực người dùng
  - name: Product
    description: Quản lý sản phẩm
  - name: User 
    description: Thông tin người dùng
  - name: Cart
    description: Các endpoint liên quan đến giỏ hàng
  - name: Admin
    description: Quản trị viên hệ thống
paths:
  # AUTH ROUTES
  /auth/login:
    $ref: './paths/auth.yaml#/auth~1login'
  /auth/register:
    $ref: './paths/auth.yaml#/auth~1register'
  /auth/logout:
    $ref: './paths/auth.yaml#/auth~1logout'
  /auth/forgot-password:
    $ref: './paths/auth.yaml#/auth~1forgot-password'
  /auth/reset-password:
    $ref: './paths/auth.yaml#/auth~1reset-password'
  /auth/google:
    $ref: './paths/auth.yaml#/auth~1google'
  /auth/google/callback:
    $ref: './paths/auth.yaml#/auth~1google~1callback'

  # USER ROUTES
  /user/me:
    $ref: './paths/user.yaml#/user~1me'
  /user/me/password:
    $ref: './paths/user.yaml#/user~1me~1password'
  /user/me/addresses:
    $ref: './paths/user.yaml#/user~1me~1addresses'
  /user/me/addresses/{id}:
    $ref: './paths/user.yaml#/user~1me~1addresses~1{id}'
  
  /user/{id}/loyalty:
      $ref: './paths/loyalty.yaml#/user~1{id}~1loyalty'

  # PRODUCT ROUTES
  /products:
    $ref: './paths/product.yaml#/products'
  /products/{id}:
    $ref: './paths/product.yaml#/products~1{id}'
  /products/{id}/variants:
    $ref: './paths/product.yaml#/products~1{id}~1variants'

  # REVIEW ROUTES
  /products/{id}/reviews:
    $ref: './paths/review.yaml#/products~1{id}~1reviews'
  /products/{id}/reviews/{id}:
    $ref: './paths/review.yaml#/products~1{id}~1reviews~1{id}'

  # ORDER ROUTES
  /orders:
    $ref: './paths/order.yaml#/orders'
  /orders/{id}:
    $ref: './paths/order.yaml#/orders~1{id}'
  /orders/{id}/tracking:
    $ref: './paths/order.yaml#/orders~1{id}~1tracking'
  /orders/{id}/payment:
    $ref: './paths/order.yaml#/orders~1{id}~1payment'

  # PAYMENT ROUTES
  /payments/vnpay/create:
    $ref: './paths/payment.yaml#/payment~1vnpay~1create'
  /payments/vnpay_return:
    $ref: './paths/payment.yaml#/payment~1vnpay_return'
  /payments/vnpay_ipn:
    $ref: './paths/payment.yaml#/payment~1vnpay_ipn'
  # ADMIN ROUTES
  /admin/dashboard/simple:
    $ref: './paths/admin.yaml#/admin~1dashboard~1simple'
  /admin/dashboard/advanced:
    $ref: './paths/admin.yaml#/admin~1dashboard~1advanced'
  /admin/users:
    $ref: './paths/admin.yaml#/admin~1users'
  /admin/users/{id}:
    $ref: './paths/admin.yaml#/admin~1users~1{id}'
  /admin/orders:
    $ref: './paths/admin.yaml#/admin~1orders'
  /admin/orders/{id}:
    $ref: './paths/admin.yaml#/admin~1orders~1{id}'
  /admin/discounts:
    $ref: './paths/admin.yaml#/admin~1discounts'
  /admin/discounts/{id}:
    $ref: './paths/admin.yaml#/admin~1discounts~1{id}'

  /carts/add:
    $ref: './paths/cart.yaml#/~1carts~1add'
  /carts/update:
    $ref: './paths/cart.yaml#/~1carts~1update'
  /carts/remove/{productId}:
    $ref: './paths/cart.yaml#/~1carts~1remove~1{productId}'
  /carts/summary:
    $ref: './paths/cart.yaml#/~1carts~1summary'
  /carts/apply-discount:
    $ref: './paths/cart.yaml#/~1carts~1apply-discount'

  /checkout/:
      $ref: './paths/checkout.yaml#/~1checkout~1'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    $ref: './components/schemas.yaml'

security:
  - bearerAuth: []


